bk.pl sucessfully generated!!!
exs.pl sucessfully generated!!!
/Users/edoardosarri/Documents/numsynth/numsynth/popper/tester.py:9: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
17:05:08 Num. pos examples: 76
17:05:08 Num. neg examples: 24
17:05:08 Searching programs of size: 3
17:05:10 Searching programs of size: 4
17:05:14 Searching programs of size: 5
17:05:41 ********************
17:05:41 New best hypothesis:
17:05:41 tp:1 fn:75 size:5
17:05:41 failure(A):- release(A,E,B),finish(A,E,F,D),release(C,E,B),execute(C,E,F,D).
17:05:41 ********************
17:05:45 ********************
17:05:45 New best hypothesis:
17:05:45 tp:1 fn:75 size:10
17:05:45 failure(A):- release(A,E,B),finish(A,E,F,D),release(C,E,B),execute(C,E,F,D).
17:05:45 failure(A):- execute(F,C,B,D),execute(F,E,B,D),complete(A,C,B),release(A,E,B).
17:05:45 ********************
17:05:45 ********************
17:05:45 New best hypothesis:
17:05:45 tp:6 fn:70 size:10
17:05:45 failure(A):- execute(F,C,B,D),execute(F,E,B,D),complete(A,C,B),release(A,E,B).
17:05:45 failure(A):- complete(F,E,D),complete(A,C,B),release(A,E,B),complete(F,C,D).
17:05:45 ********************
17:06:40 ********************
17:06:40 New best hypothesis:
17:06:40 tp:8 fn:68 size:15
17:06:40 failure(A):- finish(D,E,C,F),execute(A,E,C,F),release(A,E,B),release(D,E,B).
17:06:40 failure(A):- execute(F,C,B,D),execute(F,E,B,D),complete(A,C,B),release(A,E,B).
17:06:40 failure(A):- complete(F,E,D),complete(A,C,B),release(A,E,B),complete(F,C,D).
17:06:40 ********************
Traceback (most recent call last):
  File "/Users/edoardosarri/Documents/numsynth/numsynth/popper.py", line 8, in <module>
    prog, score, stats = learn_solution(settings)
                         ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/edoardosarri/Documents/numsynth/numsynth/popper/loop.py", line 263, in learn_solution
    timeout(settings, popper, (settings,), timeout_duration=int(settings.timeout),)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edoardosarri/Documents/numsynth/numsynth/popper/util.py", line 86, in timeout
    result = func(*args, **kwargs)
  File "/Users/edoardosarri/Documents/numsynth/numsynth/popper/loop.py", line 92, in popper
    instantiated_programs, properties = tester.test_prog(prog, selector.solution_found, settings=settings)
                                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edoardosarri/Documents/numsynth/numsynth/popper/tester.py", line 135, in test_prog
    return self.lazy_evaluation(settings, rules, numerical_reasoning, solution_found)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edoardosarri/Documents/numsynth/numsynth/popper/tester.py", line 177, in lazy_evaluation
    properties, mapping, var_clause = list(self.find_binding_prolog_numerical(settings, list(self.pos_index.keys()), rules))
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edoardosarri/Documents/numsynth/numsynth/popper/tester.py", line 262, in find_binding_prolog_numerical
    bindings = list((self.prolog.query(f'lazy_evaluation({list(pos)}, {[pred]},{[arity]},'
                                       f'{magic_args_list},{related_args_list},'
                                       f'NoSub, Pruned, Bindings)')))
  File "/opt/miniconda3/envs/numsynth/lib/python3.13/site-packages/pyswip/prolog.py", line 171, in __call__
    raise PrologError(
    ...<10 lines>...
    )
pyswip.prolog.PrologError: Caused by: 'lazy_evaluation([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76], ['failure'],[1],[[]],[[2]],NoSub, Pruned, Bindings)'. Returned: 'error(resource_error(stack), {'choicepoints': 6, 'depth': 8, 'environments': 7, 'globalused': 3, 'localused': 2, 'stack': [Functor(582029,3,8,:(system, $add_findall_bag(/(-, 2))),[]), Functor(582029,3,7,:($bags, findall_loop(/(-, 2), /(:, 2), _1086, [])),[]), Functor(582029,3,6,:($bags, cleanup_bag(/(:, 2), /(:, 2))),[]), Functor(582029,3,3,:(user, find_bindings([76], [1], [1], [1], [1], _1160)),[]), Functor(582029,3,2,:(user, lazy_evaluation([76], [1], [1], [1], [1], _1218, false, _1222)),[])], 'stack_limit': 1048576, 'trailused': 0})'.
execution time: 1m40.775s
